FEATURE_CACHED_OUTLINE: "true"
FEATURE_CHANGE_MODEL: "true"
FEATURE_ADD_CREDITS: "true"
VISIBLE_TO_USERS:
  - "5WHPxdYlmMcZtxjiJzfGdbNod472"
  - "tIhfKTNP24M9Pc1JwhzYLOceKNH3"
  - "5FSuW5bJerVCGjYAkz1H07mfIow1"
  - "6CAwM9BKjMf9PvHNmKlzn8lxlMD3"
  - "xvNcnEGc3bOYUWMM2KaSiUNX4yn1"
  - "V0aGCTq3Z4PwtD4AKS6FtkfDDJS2"
  - "KHZH2cxE0KYlt9HOJS3QjZBHEwq1"
